module.exports = {
    'ant-prefix': 'oss-ui',
    '@primary-color': '#236fab',
    '@body-background': '#000000',
    '@component-background': '#003062',
    '@icon-color': '#3FA9F5',
    '@heading-color': '#000000',
    '@text-color': '#ffffff',
    '@text-color-secondary': '#ffffff',
    '@text-color-inverse': '#ffffff',
    '@heading-color-dark': '#ffffff',
    '@text-color-secondary-dark': '#ffffff',
    '@border-color-split': '#4c6e91',
    '@layout-body-background': '#1f497a',
    '@layout-header-background': '#00264b',
    '@disabled-bg': '#2D557E',
    '@btn-disable-border': '#2D557E',
    '@item-hover-bg': '#246FAA',
    // '@btn-default-bg': '#666600',
    '@btn-default-border': '#4289b8',
    '@checkbox-color': '#4E9AEF',
    '@checkbox-check-color': '#003062',
    '@radio-dot-color': '#4E9AEF',
    '@radio-button-bg': '#003062',
    '@radio-button-checked-bg': '#003062',
    '@input-color': '#fff',
    '@input-border-color': '#0070B6',
    '@input-bg': '#003062',
    '@input-number-handler-active-bg': '#003062',
    '@select-border-color': '#0070B6',
    '@table-header-bg': '#236FAB',
    '@table-header-color': '#fff',
    '@table-row-hover-bg': '#1e5f93',
    'table-selected-row-bg': '#1e5f93',
    '@table-padding-vertical': '17px',
    '@time-picker-selected-bg': '#003062',
    '@tree-directory-selected-color': '#ffffff',
    '@modal-close-color': '#ffffff',
    '@descriptions-bg': '#003062',
    'calendar-border-color': '#003062',
    'picker-basic-cell-active-with-range-color': '#044079',
    'heading-color': '#fff',
    'font-size-base': '12px',
    'select-item-active-bg': '#064A88',
    'select-item-selected-bg': '#064A88',
    'disabled-color': '#fff',
    'tabs-card-head-background': '#003062',
    'modal-header-bg': '#3D83B6',
    'modal-header-border-width': '0',
    'modal-footer-border-width': '0',
    'modal-header-padding': '7px 24px',
    'modal-header-close-size': '36px',
    'menu-item-active-bg': '#004488',
    'menu-item-height': '35px',
    'select-selection-item-bg': '#003062',
    'table-border': '#264F79 1px solid ',
    'border-color-split': '#264F79',
    'calendar-item-active-bg': '#044083',
    'calendar-bg': '#073C70',
    'descriptions-default-padding': '5px 24px',
    'link-color': '#4E9AEF',
    'page-header-heading-title': '14px',
    'page-header-padding-vertical': '8px',
    'normal-color': '#3FA9F5',
    'collapse-header-bg': '#1C477B',
    'border-color-base': '#3372BD',
    'collapse-header-padding': '9px 16px',
    'menu-highlight-color': '#33CCFF',
    'error-color': '#FF3300',
    // vertical margins
    'margin-lg': '16px', // containers
    'margin-md': '8px', // small containers and buttons
    'margin-sm': '8px', // Form controls and items
    'margin-xs': '4px', // small items
    'margin-xss': '0px', // more small
};
