module.exports = [
    {
        path: 'lib/g-components',
        includes: ['GComponents'],
    },
    {
        path: 'lib/geometry',
        includes: ['Line', 'Interval', 'Point', 'Area', 'Polygon', 'Schema', 'Path', 'Heatmap', 'Edge', 'Geom'],
    },
    {
        path: 'lib/components',
        includes: ['Chart', 'View', 'Axis', 'Coordinate', 'Effects', 'Legend', 'Tooltip', 'Interaction'],
    },
    {
        path: 'lib/plots',
        includes: [
            'CalendarChart',
            'BulletChart',
            'BubbleChart',
            'ScatterChart',
            'WaterfallChart',
            'DonutChart',
            'HistogramChart',
            'LiquidChart',
            'RadarChart',
            'GroupedRoseChart',
            'StackedRoseChart',
            'FunnelChart',
            'RoseChart',
            'WordCloudChart',
            'HeatmapChart',
            'DensityHeatmapChart',
            'PieChart',
            'PercentStackedColumnChart',
            'RangeColumnChart',
            'StackedColumnChart',
            'GroupedColumnChart',
            'ColumnChart',
            'PercentStackedAreaChart',
            'StackedAreaChart',
            'AreaChart',
            'RangeBarChart',
            'PercentStackedBarChart',
            'GroupedBarChart',
            'StackedBarChart',
            'BarChart',
            'StepLineChart',
            'TreemapChart',
            'LineChart',
            'GaugeChart',
        ],
    },
];
